# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvbdieqysOspTX9yK0D4kGWgmaqOD48D
"""

import streamlit as st


import numpy as np
import pandas as pd
import joblib

model = joblib.load('knrpipe.joblib')
st.title('مشخصات خانه موردنظر خود را وارد کنید ')

Room = st.slider("How many room?",['0,2'])
Parking = ('yes','No')
st.radio("Have Parking?",Parking)
Elevator = ('yes','No')
st.radio("Have Elevator?",Elevator)
Address = st.selectbox("Wher is Home?",[Pardis,Parand,Dorous,Shahrake Qods,Punak])